/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package userInterface.Charts;
import business.EcoSystem;
import java.awt.Color;
import java.text.DecimalFormat;  
  
import javax.swing.JFrame;  
import javax.swing.JPanel;
import javax.swing.SwingUtilities;  
import javax.swing.WindowConstants;  
//import com.itextpdf.awt.
import org.jfree.chart.ChartFactory;  
import org.jfree.chart.ChartFrame;
import org.jfree.chart.ChartPanel;  
import org.jfree.chart.JFreeChart;  
import org.jfree.chart.labels.PieSectionLabelGenerator;  
import org.jfree.chart.labels.StandardPieSectionLabelGenerator;  
import org.jfree.chart.plot.CategoryPlot;
import org.jfree.chart.plot.PiePlot;  
import org.jfree.chart.plot.PlotOrientation;
import org.jfree.data.category.DefaultCategoryDataset;
import org.jfree.data.general.DefaultPieDataset;  
import org.jfree.data.general.PieDataset;  
/**
 *
 * @author amisha03
 */
public class PieChartJPanel extends javax.swing.JPanel {

    /**
     * Creates new form PieChartJPanel
     */
    JPanel userProcessContainer;
    EcoSystem ecosystem;
    public PieChartJPanel(JPanel userProcessContainer,EcoSystem ecosystem) {
        initComponents();
        this.ecosystem = ecosystem;
        this.userProcessContainer= userProcessContainer;
       //  super(title);  
  
    // Create dataset  
    PieDataset dataset = createDataset();  
  
    // Create chart  
    JFreeChart chart = ChartFactory.createPieChart(  
        "Pie Chart Example",  
        dataset,  
        true,   
        true,  
        false);  
  
    //Format Label  
    PieSectionLabelGenerator labelGenerator = new StandardPieSectionLabelGenerator(  
        "Marks {0} : ({2})", new DecimalFormat("0"), new DecimalFormat("0%"));  
    ((PiePlot) chart.getPlot()).setLabelGenerator(labelGenerator);  
      
    // Create Panel  
    ChartPanel panel = new ChartPanel(chart);  
    //(panel);  
    
     
   
    }
    
     private PieDataset createDataset() {  
  
    DefaultPieDataset dataset=new DefaultPieDataset();  
    dataset.setValue("80-100", 120);  
    dataset.setValue("60-79", 80);  
    dataset.setValue("40-59", 20);  
    dataset.setValue("20-39", 7);  
    dataset.setValue("0-19", 3);  
    return dataset;  
  }  

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jButton1 = new javax.swing.JButton();

        jButton1.setText("jButton1");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(112, 112, 112)
                .addComponent(jButton1)
                .addContainerGap(213, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(55, 55, 55)
                .addComponent(jButton1)
                .addContainerGap(222, Short.MAX_VALUE))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        // TODO add your handling code here:
        DefaultCategoryDataset dataset = new DefaultCategoryDataset();  
  
    // Population in 2005  
    dataset.addValue(10, "USA", "2005");  
    dataset.addValue(15, "India", "2005");  
    dataset.addValue(20, "China", "2005");  
  
    // Population in 2010  
    dataset.addValue(15, "USA", "2010");  
    dataset.addValue(20, "India", "2010");  
    dataset.addValue(25, "China", "2010");  
  
    // Population in 2015  
    dataset.addValue(20, "USA", "2015");  
    dataset.addValue(25, "India", "2015");  
    dataset.addValue(30, "China", "2015");  
    
    
     JFreeChart chart=ChartFactory.createBarChart(  
        "Bar Chart Example", //Chart Title  
        "Year", // Category axis  
        "Population in Million", // Value axis  
        dataset,  
        PlotOrientation.VERTICAL,  
        true,true,false  
       );  
       ChartFrame chartFrame = new ChartFrame("Medicines",chart,true);
       chartFrame.setVisible(true);
       chartFrame.setSize(2000,1000); 
     CategoryPlot plot = chart.getCategoryPlot();
       plot.setRangeGridlinePaint(Color.BLACK);
    
        
    }//GEN-LAST:event_jButton1ActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton1;
    // End of variables declaration//GEN-END:variables
}
