/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package ui;

import java.sql.Connection;
import java.sql.DriverManager;
import java.sql.Statement;
import javax.swing.JOptionPane;

/**
 *
 * @author sri_sai_nikhil_enni
 */
public class HomePage extends javax.swing.JFrame {

    /**
     * Creates new form HomePage
     */
    public HomePage() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        buttonGroup1 = new javax.swing.ButtonGroup();
        jSplitPane1 = new javax.swing.JSplitPane();
        jControlPanel = new javax.swing.JPanel();
        jHomeBtn = new javax.swing.JButton();
        jCityAdminBtn = new javax.swing.JButton();
        jHomePage = new javax.swing.JPanel();
        jTabbedPane1 = new javax.swing.JTabbedPane();
        jRegistration = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jPatID = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        jHospital = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        jDept = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        jDoctor = new javax.swing.JTextField();
        jBookAppointment = new javax.swing.JButton();
        jButton1 = new javax.swing.JButton();
        jPatientForm = new javax.swing.JPanel();
        jLabel5 = new javax.swing.JLabel();
        jPatName = new javax.swing.JTextField();
        jLabel6 = new javax.swing.JLabel();
        jPatSSN = new javax.swing.JTextField();
        jLabel7 = new javax.swing.JLabel();
        jPatAge = new javax.swing.JTextField();
        jLabel8 = new javax.swing.JLabel();
        jRadioButton1 = new javax.swing.JRadioButton();
        jRadioButton2 = new javax.swing.JRadioButton();
        jRadioButton3 = new javax.swing.JRadioButton();
        jLabel9 = new javax.swing.JLabel();
        jPatPhnNum = new javax.swing.JTextField();
        jLabel10 = new javax.swing.JLabel();
        jPatEmail = new javax.swing.JTextField();
        jSaveBtn = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();
        jLabel16 = new javax.swing.JLabel();
        jPatPassword = new javax.swing.JPasswordField();
        jLabel17 = new javax.swing.JLabel();
        jPatConfirmPass = new javax.swing.JPasswordField();
        jDoctorForm = new javax.swing.JPanel();
        jLabel11 = new javax.swing.JLabel();
        jDocName = new javax.swing.JTextField();
        jLabel12 = new javax.swing.JLabel();
        jDocSSN = new javax.swing.JTextField();
        jLabel13 = new javax.swing.JLabel();
        jDocAge = new javax.swing.JTextField();
        jLabel14 = new javax.swing.JLabel();
        jDocPhnNum = new javax.swing.JTextField();
        jLabel15 = new javax.swing.JLabel();
        jDocEmail = new javax.swing.JTextField();
        jDocSave = new javax.swing.JButton();
        jDocClear = new javax.swing.JButton();
        jLabel18 = new javax.swing.JLabel();
        jDocPassword = new javax.swing.JPasswordField();
        jLabel19 = new javax.swing.JLabel();
        jDocConfirmPass = new javax.swing.JPasswordField();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jHomeBtn.setText("Home");
        jHomeBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jHomeBtnActionPerformed(evt);
            }
        });

        jCityAdminBtn.setText("Facilities");
        jCityAdminBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jCityAdminBtnActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jControlPanelLayout = new javax.swing.GroupLayout(jControlPanel);
        jControlPanel.setLayout(jControlPanelLayout);
        jControlPanelLayout.setHorizontalGroup(
            jControlPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jControlPanelLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jControlPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jHomeBtn, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jCityAdminBtn, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap())
        );
        jControlPanelLayout.setVerticalGroup(
            jControlPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jControlPanelLayout.createSequentialGroup()
                .addGap(23, 23, 23)
                .addComponent(jHomeBtn)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jCityAdminBtn)
                .addContainerGap(308, Short.MAX_VALUE))
        );

        jSplitPane1.setLeftComponent(jControlPanel);

        jLabel1.setText("Patient Id:");

        jPatID.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jPatIDActionPerformed(evt);
            }
        });

        jLabel2.setText("Hospital:");

        jLabel3.setText("Department:");

        jLabel4.setText("Doctor:");

        jBookAppointment.setText("Book Appointment");
        jBookAppointment.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jBookAppointmentActionPerformed(evt);
            }
        });

        jButton1.setText("Clear");

        javax.swing.GroupLayout jRegistrationLayout = new javax.swing.GroupLayout(jRegistration);
        jRegistration.setLayout(jRegistrationLayout);
        jRegistrationLayout.setHorizontalGroup(
            jRegistrationLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jRegistrationLayout.createSequentialGroup()
                .addGap(26, 26, 26)
                .addGroup(jRegistrationLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jRegistrationLayout.createSequentialGroup()
                        .addComponent(jBookAppointment)
                        .addGap(18, 18, 18)
                        .addComponent(jButton1))
                    .addGroup(jRegistrationLayout.createSequentialGroup()
                        .addGroup(jRegistrationLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel1)
                            .addComponent(jLabel2)
                            .addComponent(jLabel3)
                            .addComponent(jLabel4))
                        .addGap(33, 33, 33)
                        .addGroup(jRegistrationLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(jPatID)
                            .addComponent(jHospital)
                            .addComponent(jDept)
                            .addComponent(jDoctor, javax.swing.GroupLayout.DEFAULT_SIZE, 207, Short.MAX_VALUE))))
                .addContainerGap(263, Short.MAX_VALUE))
        );
        jRegistrationLayout.setVerticalGroup(
            jRegistrationLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jRegistrationLayout.createSequentialGroup()
                .addGap(14, 14, 14)
                .addGroup(jRegistrationLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(jPatID, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jRegistrationLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(jHospital, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jRegistrationLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3)
                    .addComponent(jDept, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jRegistrationLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel4)
                    .addComponent(jDoctor, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jRegistrationLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jBookAppointment)
                    .addComponent(jButton1))
                .addContainerGap(175, Short.MAX_VALUE))
        );

        jTabbedPane1.addTab("Registration", jRegistration);

        jLabel5.setText("Patient Name:");

        jLabel6.setText("Patient SSN:");

        jLabel7.setText("Age:");

        jLabel8.setText("Gender:");

        buttonGroup1.add(jRadioButton1);
        jRadioButton1.setText("Male");
        jRadioButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jRadioButton1ActionPerformed(evt);
            }
        });

        buttonGroup1.add(jRadioButton2);
        jRadioButton2.setText("Female");

        buttonGroup1.add(jRadioButton3);
        jRadioButton3.setText("Prefer not to say");

        jLabel9.setText("Phone Number:");

        jLabel10.setText("Email:");

        jSaveBtn.setText("Save");
        jSaveBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jSaveBtnActionPerformed(evt);
            }
        });

        jButton2.setText("Clear");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });

        jLabel16.setText("Password:");

        jLabel17.setText("Confirm Password:");

        javax.swing.GroupLayout jPatientFormLayout = new javax.swing.GroupLayout(jPatientForm);
        jPatientForm.setLayout(jPatientFormLayout);
        jPatientFormLayout.setHorizontalGroup(
            jPatientFormLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPatientFormLayout.createSequentialGroup()
                .addGap(25, 25, 25)
                .addGroup(jPatientFormLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPatientFormLayout.createSequentialGroup()
                        .addComponent(jSaveBtn)
                        .addGap(18, 18, 18)
                        .addComponent(jButton2)
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(jPatientFormLayout.createSequentialGroup()
                        .addGroup(jPatientFormLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel5)
                            .addComponent(jLabel6)
                            .addComponent(jLabel7)
                            .addComponent(jLabel8)
                            .addComponent(jLabel9)
                            .addComponent(jLabel10)
                            .addComponent(jLabel16)
                            .addComponent(jLabel17))
                        .addGap(23, 23, 23)
                        .addGroup(jPatientFormLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jPatAge)
                            .addComponent(jPatSSN)
                            .addGroup(jPatientFormLayout.createSequentialGroup()
                                .addComponent(jRadioButton1, javax.swing.GroupLayout.PREFERRED_SIZE, 51, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(jRadioButton2)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(jRadioButton3)
                                .addGap(0, 7, Short.MAX_VALUE))
                            .addComponent(jPatName)
                            .addComponent(jPatPhnNum)
                            .addComponent(jPatEmail)
                            .addComponent(jPatPassword)
                            .addComponent(jPatConfirmPass))
                        .addGap(176, 176, 176))))
        );
        jPatientFormLayout.setVerticalGroup(
            jPatientFormLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPatientFormLayout.createSequentialGroup()
                .addGap(19, 19, 19)
                .addGroup(jPatientFormLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel5)
                    .addComponent(jPatName, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPatientFormLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel6)
                    .addComponent(jPatSSN, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPatientFormLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel7)
                    .addComponent(jPatAge, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPatientFormLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel8)
                    .addComponent(jRadioButton1)
                    .addComponent(jRadioButton2)
                    .addComponent(jRadioButton3))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPatientFormLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel9)
                    .addComponent(jPatPhnNum, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPatientFormLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel10)
                    .addComponent(jPatEmail, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPatientFormLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel16)
                    .addComponent(jPatPassword, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPatientFormLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel17)
                    .addComponent(jPatConfirmPass, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 45, Short.MAX_VALUE)
                .addGroup(jPatientFormLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jSaveBtn)
                    .addComponent(jButton2))
                .addGap(29, 29, 29))
        );

        jTabbedPane1.addTab("Patient Form", jPatientForm);

        jLabel11.setText("Doctor Name:");

        jLabel12.setText("Doctor SSN:");

        jLabel13.setText("Age:");

        jLabel14.setText("Phone Number:");

        jLabel15.setText("Email:");

        jDocSave.setText("Save");
        jDocSave.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jDocSaveActionPerformed(evt);
            }
        });

        jDocClear.setText("Clear");

        jLabel18.setText("Password:");

        jLabel19.setText("Confirm Password:");

        javax.swing.GroupLayout jDoctorFormLayout = new javax.swing.GroupLayout(jDoctorForm);
        jDoctorForm.setLayout(jDoctorFormLayout);
        jDoctorFormLayout.setHorizontalGroup(
            jDoctorFormLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jDoctorFormLayout.createSequentialGroup()
                .addGap(24, 24, 24)
                .addGroup(jDoctorFormLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jDoctorFormLayout.createSequentialGroup()
                        .addComponent(jDocSave)
                        .addGap(18, 18, 18)
                        .addComponent(jDocClear))
                    .addGroup(jDoctorFormLayout.createSequentialGroup()
                        .addGroup(jDoctorFormLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel11)
                            .addComponent(jLabel12)
                            .addComponent(jLabel13)
                            .addComponent(jLabel14)
                            .addComponent(jLabel15)
                            .addComponent(jLabel18)
                            .addComponent(jLabel19))
                        .addGap(30, 30, 30)
                        .addGroup(jDoctorFormLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(jDocName)
                            .addComponent(jDocSSN)
                            .addComponent(jDocAge)
                            .addComponent(jDocPhnNum)
                            .addComponent(jDocEmail)
                            .addComponent(jDocPassword)
                            .addComponent(jDocConfirmPass, javax.swing.GroupLayout.DEFAULT_SIZE, 214, Short.MAX_VALUE))))
                .addContainerGap(222, Short.MAX_VALUE))
        );
        jDoctorFormLayout.setVerticalGroup(
            jDoctorFormLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jDoctorFormLayout.createSequentialGroup()
                .addGap(18, 18, 18)
                .addGroup(jDoctorFormLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel11)
                    .addComponent(jDocName, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jDoctorFormLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel12)
                    .addComponent(jDocSSN, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jDoctorFormLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel13)
                    .addComponent(jDocAge, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jDoctorFormLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel14)
                    .addComponent(jDocPhnNum, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jDoctorFormLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel15)
                    .addComponent(jDocEmail, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jDoctorFormLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel18)
                    .addComponent(jDocPassword, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jDoctorFormLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel19)
                    .addComponent(jDocConfirmPass, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jDoctorFormLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jDocSave)
                    .addComponent(jDocClear))
                .addContainerGap(84, Short.MAX_VALUE))
        );

        jTabbedPane1.addTab("Doctor Form", jDoctorForm);

        javax.swing.GroupLayout jHomePageLayout = new javax.swing.GroupLayout(jHomePage);
        jHomePage.setLayout(jHomePageLayout);
        jHomePageLayout.setHorizontalGroup(
            jHomePageLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jHomePageLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jTabbedPane1)
                .addContainerGap())
        );
        jHomePageLayout.setVerticalGroup(
            jHomePageLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jHomePageLayout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jTabbedPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 371, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );

        jSplitPane1.setRightComponent(jHomePage);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jSplitPane1)
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jSplitPane1)
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jPatIDActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jPatIDActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jPatIDActionPerformed

    private void jBookAppointmentActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jBookAppointmentActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jBookAppointmentActionPerformed

    private void jRadioButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jRadioButton1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jRadioButton1ActionPerformed

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jButton2ActionPerformed

    private void jDocSaveActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jDocSaveActionPerformed
        String doctorName=jDocName.getText();
        String docSSN=jDocSSN.getText();
        int docAge=Integer.valueOf(jDocAge.getText());
        Long docPhn=Long.valueOf(jDocPhnNum.getText());
        String docEmail=jDocEmail.getText();
        
        String password=null;
        if(jDocPassword.getText().equals(jDocConfirmPass.getText())){
            password=jDocPassword.getText();
        }else{
            JOptionPane.showMessageDialog(jDocSave, "Passwords do not match.");
        }

        try{
            Connection connection = DriverManager.getConnection("jdbc:mysql://localhost:3306/Elixir", "root", "password");
            String query_pat = "INSERT INTO Doctors VALUES(null,'" + doctorName + "','" + docSSN + "','" + docAge + "','" + docPhn + "','" + docEmail + "')";
            String query_user_acc="INSERT INTO User_Accounts VALUES('" + docSSN + "','" + password + "')";

                    Statement sta = connection.createStatement();
                    int x = sta.executeUpdate(query_pat);
                    int y = sta.executeUpdate(query_user_acc);
                    if (x == 0 || y==0) {
                        JOptionPane.showMessageDialog(jSaveBtn, "This is alredy exist");
                    } else {
                        JOptionPane.showMessageDialog(jSaveBtn,
                            "Welcome, Your account is sucessfully created");
                    }
                    connection.close();
        } catch (Exception exception) {
                    exception.printStackTrace();
        }
    }//GEN-LAST:event_jDocSaveActionPerformed

    private void jSaveBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jSaveBtnActionPerformed
        String patientName=jPatName.getText();
        String patSSN=jPatSSN.getText();
        int patAge=Integer.valueOf(jPatAge.getText());
        Long patPhn=Long.valueOf(jPatPhnNum.getText());
        String patEmail=jPatEmail.getText();
        
        String password=null;
        if(jPatPassword.getText().equals(jPatConfirmPass.getText())){
            password=jPatPassword.getText();
        }else{
            JOptionPane.showMessageDialog(jSaveBtn, "Passwords do not match.");
        }

        try{
            Connection connection = DriverManager.getConnection("jdbc:mysql://localhost:3306/Elixir", "root", "password");
            String query_pat = "INSERT INTO Patients VALUES(null,'" + patientName + "','" + patAge + "','" + patSSN + "','" + patPhn + "','" + patEmail + "')";
            String query_user_acc="INSERT INTO User_Accounts VALUES('" + patSSN + "','" + password + "')";

                    Statement sta = connection.createStatement();
                    int x = sta.executeUpdate(query_pat);
                    int y = sta.executeUpdate(query_user_acc);
                    if (x == 0 || y==0) {
                        JOptionPane.showMessageDialog(jSaveBtn, "This is alredy exist");
                    } else {
                        JOptionPane.showMessageDialog(jSaveBtn,
                            "Welcome, Your account is sucessfully created");
                    }
                    connection.close();
        } catch (Exception exception) {
                    exception.printStackTrace();
        }
    }//GEN-LAST:event_jSaveBtnActionPerformed

    private void jHomeBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jHomeBtnActionPerformed
        HomePage home=new HomePage();
        jSplitPane1.setRightComponent(home.jHomePage);
    }//GEN-LAST:event_jHomeBtnActionPerformed

    private void jCityAdminBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jCityAdminBtnActionPerformed
        CityAdminPage cityAdmin=new CityAdminPage();
        jSplitPane1.setRightComponent(cityAdmin);
    }//GEN-LAST:event_jCityAdminBtnActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(HomePage.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(HomePage.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(HomePage.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(HomePage.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new HomePage().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.ButtonGroup buttonGroup1;
    private javax.swing.JButton jBookAppointment;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jCityAdminBtn;
    private javax.swing.JPanel jControlPanel;
    private javax.swing.JTextField jDept;
    private javax.swing.JTextField jDocAge;
    private javax.swing.JButton jDocClear;
    private javax.swing.JPasswordField jDocConfirmPass;
    private javax.swing.JTextField jDocEmail;
    private javax.swing.JTextField jDocName;
    private javax.swing.JPasswordField jDocPassword;
    private javax.swing.JTextField jDocPhnNum;
    private javax.swing.JTextField jDocSSN;
    private javax.swing.JButton jDocSave;
    private javax.swing.JTextField jDoctor;
    private javax.swing.JPanel jDoctorForm;
    private javax.swing.JButton jHomeBtn;
    private javax.swing.JPanel jHomePage;
    private javax.swing.JTextField jHospital;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JLabel jLabel17;
    private javax.swing.JLabel jLabel18;
    private javax.swing.JLabel jLabel19;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JTextField jPatAge;
    private javax.swing.JPasswordField jPatConfirmPass;
    private javax.swing.JTextField jPatEmail;
    private javax.swing.JTextField jPatID;
    private javax.swing.JTextField jPatName;
    private javax.swing.JPasswordField jPatPassword;
    private javax.swing.JTextField jPatPhnNum;
    private javax.swing.JTextField jPatSSN;
    private javax.swing.JPanel jPatientForm;
    private javax.swing.JRadioButton jRadioButton1;
    private javax.swing.JRadioButton jRadioButton2;
    private javax.swing.JRadioButton jRadioButton3;
    private javax.swing.JPanel jRegistration;
    private javax.swing.JButton jSaveBtn;
    private javax.swing.JSplitPane jSplitPane1;
    private javax.swing.JTabbedPane jTabbedPane1;
    // End of variables declaration//GEN-END:variables
}
