/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

package userInterface.MedicineUnitArea;


import business.EcoSystem;
import business.enterprise.Enterprise;
import business.medicine.Medicine;
import business.medicine.MedicineList;
import business.network.Network;
import business.organization.BillingOrganization;
import business.organization.MedicineOrganization;
import business.organization.Organization;

import business.userAccount.UserAccount;


import business.workQueue.WorkRequest;

import java.awt.CardLayout;
import java.util.ArrayList;
import javax.swing.JOptionPane;
import javax.swing.JPanel;
import javax.swing.table.DefaultTableModel;
import org.apache.log4j.Logger;
/**
 *
 * @author sri_sai_nikhil_enni
 */
public class PharmacyWorkArea extends javax.swing.JPanel {

    /**
     * Creates new form PharmacyWorkArea
     */
    JPanel userProcessContainer;
    private UserAccount userAccount;
    private Enterprise enterprise;
    private EcoSystem ecoSystem;
//    private MedicalInventoryList mil;
    private Organization org;
    private MedicineOrganization pharmorg;
    private Network network;
    private static Logger log = Logger.getLogger(PharmacyWorkArea2.class);
    private static final String CLASS_NAME = PharmacyWorkArea2.class.getName();

    public PharmacyWorkArea(JPanel userProcessContainer, UserAccount userAccount, Organization organization, Enterprise enterprise, 
            Network network,EcoSystem ecoSystem) {
        initComponents();
         this.userProcessContainer = userProcessContainer;
        this.userAccount = userAccount;
        this.enterprise = enterprise;
//        this.pharmorg = organization;
        this.network = network;
        this.ecoSystem = ecoSystem;
        
//        populateDocTable();
        log.debug(userAccount+" "+"logged in");
         Organization medicineOrg = null;
      
            for(Enterprise enrise : network.getEnterpriseDirectory().getEnterpriseList())  
            {
              for (Organization org : enrise.getOrganizationDirectory().getOrganizationList()) {
                  if(org instanceof MedicineOrganization)
                  {
                         this.pharmorg = (MedicineOrganization) org;
                        
                         break;
                     }
                 }
            }
       reorderTable();
    }

    public void reorderTable() {
        int rowCount = reorderTable.getRowCount();
        DefaultTableModel model = (DefaultTableModel) reorderTable.getModel();
        for (int i = rowCount - 1; i >= 0; i--) {
            model.removeRow(i);
        }
        for (Medicine mi : pharmorg.getMedList()) {
            Object row[] = new Object[4];
            row[0] = mi;
            row[1] = mi.getSerialNumber();
            row[2] = mi.getAvailQuantity();
            row[3] = mi.getReorderStatus();
           // row[4] = 
            //row[5] = mi.getReorderStatus();
            model.addRow(row);
        }
    }
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        reorderTable = new javax.swing.JTable();
        jLabel2 = new javax.swing.JLabel();
        serialNumberTxtField = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        medicineNameTxtField = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        availQuantityTxtField = new javax.swing.JTextField();
        jLabel5 = new javax.swing.JLabel();
        jComboBox1 = new javax.swing.JComboBox<>();
        btnAddMedicine = new javax.swing.JButton();
        jLabel6 = new javax.swing.JLabel();

        setBackground(new java.awt.Color(255, 255, 255));
        setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setFont(new java.awt.Font("SansSerif", 1, 18)); // NOI18N
        jLabel1.setText("PHARMACY WORK AREA");
        add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(315, 19, 257, 38));

        reorderTable.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Medicine", "Serial Number", "Available Quantity", "Status"
            }
        ));
        jScrollPane1.setViewportView(reorderTable);

        add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(36, 109, 794, 140));

        jLabel2.setText("Serial Number:");
        add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(221, 286, -1, -1));
        add(serialNumberTxtField, new org.netbeans.lib.awtextra.AbsoluteConstraints(363, 279, 250, 30));

        jLabel3.setText("Medicine Name :");
        add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(209, 346, -1, -1));
        add(medicineNameTxtField, new org.netbeans.lib.awtextra.AbsoluteConstraints(363, 339, 250, 30));

        jLabel4.setText("Available Quantity: ");
        add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(190, 407, -1, 14));
        add(availQuantityTxtField, new org.netbeans.lib.awtextra.AbsoluteConstraints(363, 399, 250, 30));

        jLabel5.setText("Status :");
        add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(266, 465, -1, -1));

        jComboBox1.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "", "Available", "Not Available" }));
        jComboBox1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jComboBox1ActionPerformed(evt);
            }
        });
        add(jComboBox1, new org.netbeans.lib.awtextra.AbsoluteConstraints(363, 459, 250, 30));

        btnAddMedicine.setText("Add Medicine");
        btnAddMedicine.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAddMedicineActionPerformed(evt);
            }
        });
        add(btnAddMedicine, new org.netbeans.lib.awtextra.AbsoluteConstraints(363, 507, 250, 30));

        jLabel6.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Image/medicine.jpg"))); // NOI18N
        add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 340, 960, 350));
    }// </editor-fold>//GEN-END:initComponents

    private void btnAddMedicineActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAddMedicineActionPerformed
        // TODO add your handling code here:
        
         Medicine m = new Medicine();
        String name = medicineNameTxtField.getText().trim();
        String error_message = "";
        String avail = availQuantityTxtField.getText();
        try {
            Integer.parseInt(avail);
        } catch (NumberFormatException e) {
            JOptionPane.showMessageDialog(null, "Available quantity must be integer");
            return;

        }
        if(name.isEmpty())
        {
            JOptionPane.showMessageDialog(null, "Please enter the name ");
            return;
        }
        
        m.setMedicineName(medicineNameTxtField.getText());
        try{
        int availableQuantity = Integer.parseInt(availQuantityTxtField.getText());
        m.setAvailQuantity(availableQuantity);
        }
        catch (NumberFormatException e) {
            JOptionPane.showMessageDialog(null, "serial number must be integer!");
            return;
        }
        try{
        int serialNumber = Integer.parseInt(serialNumberTxtField.getText());
        m.setSerialNumber(serialNumber);
        }
        catch (NumberFormatException e) {
            JOptionPane.showMessageDialog(null, "serial number must be integer!");
            return;
        }
        //String req = reqQuantityTxtField.getText();
        try {
           
           // m.setRequiredQuantity( Integer.parseInt(req));
        } catch (NumberFormatException e) {

            JOptionPane.showMessageDialog(null, "Required quantity must be integer!");
            return;
        }
       
//        ArrayList<String> medicineCheck = new ArrayList<>();
//        for(MedicalInventory mc:pharmorg.getMedList())
//        {
//            medicineCheck.add(mc.getMedicineName().toLowerCase());
//        }
//        if(medicineCheck.contains(name.toLowerCase()))
//        {
//            JOptionPane.showMessageDialog(null, "medicine already existed please update the quantity by clicking on view details");
//            return;
//        }
    String status =  jComboBox1.getSelectedItem().toString();
    System.out.println(status);
        m.setReorderStatus(status);
        pharmorg.addMedicine(m);
       
        
        

        DefaultTableModel dtm = (DefaultTableModel) reorderTable.getModel();

        dtm.setRowCount(0);
        for (Medicine mi : pharmorg.getMedList()) {
            Object row[] = new Object[4];
            row[0] = mi;
            row[1] = mi.getSerialNumber();
            row[2] = mi.getAvailQuantity();
            row[3] =  mi.getReorderStatus();
          
            dtm.addRow(row);
        }

        JOptionPane.showMessageDialog(null, "Medicine Added Successfully", "Warning", JOptionPane.INFORMATION_MESSAGE);
        log.debug("medicine added successfully");
        serialNumberTxtField.setText("");
        medicineNameTxtField.setText("");
        availQuantityTxtField.setText("");
        //reqQuantityTxtField.setText("");
        
    }//GEN-LAST:event_btnAddMedicineActionPerformed

    private void jComboBox1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jComboBox1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jComboBox1ActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextField availQuantityTxtField;
    private javax.swing.JButton btnAddMedicine;
    private javax.swing.JComboBox<String> jComboBox1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTextField medicineNameTxtField;
    private javax.swing.JTable reorderTable;
    private javax.swing.JTextField serialNumberTxtField;
    // End of variables declaration//GEN-END:variables
}
