/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package userInterface.EquipementWorkArea;

import Business.EcoSystem;
import Business.Employee.Employee;
import Business.Enterprise.Enterprise;
import Business.Equipment.Equipment;
import Business.Equipment.EquipmentList;
import Business.Network.Network;
import Business.Organization.Organization;
import Business.UserAccount.UserAccount;
import java.awt.CardLayout;
import javax.swing.JPanel;
import javax.swing.table.DefaultTableModel;
import userinterface.EmergencyUnitAdminArea.EmergencyUnitManageEmployeeJPanel;

/**
 *
 * @author amisha03
 */
public class EquipmentWorkAreaJPanel extends javax.swing.JPanel {

    /**
     * Creates new form EquipmentWorkAreaJPanel
     */
    JPanel userProcessContainer;
    Enterprise enterprise;
    EcoSystem ecosystem;
    EquipmentList equipmentList;
    Network network;
    UserAccount userAccount;
    Organization organization;
    public EquipmentWorkAreaJPanel(JPanel userProcessContainer, UserAccount userAccount,Network network, Enterprise enterprise,
            Organization organization,EcoSystem ecosystem) {
        initComponents();
        this.userProcessContainer = userProcessContainer;
        this.enterprise = enterprise;
        this.ecosystem = ecosystem;
        this.equipmentList = ecosystem.getEquipmentList();
        this.network = network;
        this.userAccount = userAccount;
        this.organization = organization;
        populateTable();
    }
    
    public void populateTable()
    {
         DefaultTableModel model = (DefaultTableModel) tblEquipList.getModel();

        model.setRowCount(0);

        for (Equipment equipment : ecosystem.getEquipmentList().getEquipmentList()) {
            Object[] row = new Object[5];
            double cost = equipment.getCost();
            int qunt = Integer.parseInt(equipment.getAvailableQuant());
            row[0] = equipment.getEquipmentID();
            row[1] = equipment.getEquipmetName();
            row[2] = equipment.getAvailableQuant();
            row[3] = equipment.getCost();
            row[4] = cost * qunt ;
            model.addRow(row);
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        buttonGroup1 = new javax.swing.ButtonGroup();
        jLabel1 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        tblEquipList = new javax.swing.JTable();
        jButton1 = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();
        jLabel3 = new javax.swing.JLabel();

        setBackground(new java.awt.Color(255, 255, 255));
        setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setFont(new java.awt.Font("Lucida Grande", 1, 24)); // NOI18N
        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        jLabel1.setText("EQUIPMENT ADMIN PAGE");
        add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(270, 19, -1, 40));

        tblEquipList.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null}
            },
            new String [] {
                "Equipment ID", "Equipment Name", "Available Quantity", "Equipment Cost", "Total Cost"
            }
        ));
        jScrollPane1.setViewportView(tblEquipList);

        add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(91, 89, 668, 183));

        jButton1.setText("Add New Equipment");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        add(jButton1, new org.netbeans.lib.awtextra.AbsoluteConstraints(133, 322, 220, -1));

        jButton2.setText("Request for Equipment");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });
        add(jButton2, new org.netbeans.lib.awtextra.AbsoluteConstraints(481, 322, 220, -1));

        jLabel3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Image/equipmentworkarea.png"))); // NOI18N
        add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 800, 570));
    }// </editor-fold>//GEN-END:initComponents

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        // TODO add your handling code here:
         AddEquipmentJPanel mujp = new AddEquipmentJPanel(userProcessContainer, enterprise, ecosystem);
        userProcessContainer.add("AddEquipmentJPanel",mujp);
        CardLayout layout = (CardLayout) userProcessContainer.getLayout();
        layout.next(userProcessContainer);
    }//GEN-LAST:event_jButton1ActionPerformed

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        // TODO add your handling code here:
         EquipmentRequestJPanel mujp = new EquipmentRequestJPanel(userProcessContainer,network, enterprise,organization , userAccount,ecosystem);
        userProcessContainer.add("AddEquipmentJPanel",mujp);
        CardLayout layout = (CardLayout) userProcessContainer.getLayout();
        layout.next(userProcessContainer);
    }//GEN-LAST:event_jButton2ActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.ButtonGroup buttonGroup1;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable tblEquipList;
    // End of variables declaration//GEN-END:variables
}
